language: python
python:
  - 2.7
  - 3.5
  - "pypy"
install:
  - pip install .
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
